config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  protect_from_forgery with: :exception, unless: -> {request.format.json?}
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

  <p>
    <strong>Published:</strong>
    <%= article.published %>
  </p>

</div>

app/views/articles/_form.html.erb
<div class="container">
  <%= form_with model: article, class: 'needs-validation', novalidate: true do |form| %>
    <div class="row">
      <div class="col-md-6">
        <div class="mb-3">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: "form-control", required: true %>
          <% article.errors.full_messages_for(:title).each do |message| %>
            <div class="invalid-feedback"><%= message %></div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="mb-3">
          <%= form.label :body, class: "form-label" %>
          <%= form.text_area :body, class: "form-control", rows: 5, required: true %>
          <% article.errors.full_messages_for(:body).each do |message| %>
            <div class="invalid-feedback"><%= message %></div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="mb-3 form-check">
          <%= form.check_box :published, class: "form-check-input" %>
          <%= form.label :published, class: "form-check-label" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <nav class="navbar fixed-top navbar-dark bg-primary">
    <h1 class="navbar-text text-center">
      BLOG POST
      <small class="text-muted">Powered by Rails</small>
    </h1>
  </nav>
</div>

<div class="container pt-5 mt-5">
<h1>Editing article</h1>
<%= render "form", article: @article %>
<br>
  <div class="container pt-5 mt-5">
    <%= link_to "Show this article", @article, class: "btn btn-warning" %>  
    <%= link_to "Back to articles", articles_path, class: 'btn btn-secondary mt-2' %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <nav class="navbar fixed-top navbar-dark bg-primary">
    <h1 class="navbar-text text-center">
      BLOG POST
      <small class="text-muted">Powered by Rails</small>
    </h1>
  </nav>
</div>
<p style="color: green"><%= notice %></p>

<div class="container pt-5 mt-5">
  <h1>Articles</h1>

  <div id="articles">
    <% @articles.each do |article| %>
      <%= render article %>
      <p>
        <%= link_to "Show this article", article %>
      </p>
    <% end %>
  </div>

  <%= link_to "New article", new_article_path, class: "btn btn-primary mt-3" %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <nav class="navbar fixed-top navbar-dark bg-primary">
    <h1 class="navbar-text text-center">
      BLOG POST
      <small class="text-muted">Powered by Rails</small>
    </h1>
  </nav>
</div>

<div class="container pt-5 mt-5">
<h1>New article</h1>

<%= render "form", article: @article %>

  <br>
  <div>
    <%= link_to "Back to articles", articles_path, class: 'btn btn-secondary mt-2' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <nav class="navbar fixed-top navbar-dark bg-primary">
    <h1 class="navbar-text text-center">
      BLOG POST
      <small class="text-muted">Powered by Rails</small>      
    </h1>
  </nav>
</div>
<p style="color: green"><%= notice %></p>
<div class="container pt-5 mt-5">
<%= render @article %>

  <div class="container pt-5 mt-5">
    <ul class="list-inline">
      <li class="list-inline-item"><%= link_to "Edit", edit_article_path(@article), class: "btn btn-warning" %></li>
      <li class="list-inline-item"><%= link_to "Destroy", article_path(@article), data: {turbo_method: :delete, 
      turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %></li>
    </ul>

    <%= link_to 'Back', articles_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Post</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>